// <auto-generated />
namespace VipControle.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class update_07122017 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_07122017));
        
        string IMigrationMetadata.Id
        {
            get { return "201712071848071_update_07122017"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
